# Generated by Django 5.0.4 on 2025-04-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='barrio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='horario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='url_imagen',
            field=models.URLField(null=True),
        ),
    ]
