# Generated by Django 5.0.4 on 2025-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_servicio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('file_path', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen Subida',
                'verbose_name_plural': 'Imágenes Subidas',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
