# Generated by Django 5.0.4 on 2025-05-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueo',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cita'),
        ),
    ]
